# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c59bccf04370ce70286821c7232f05d74be23da3e5ed93c393f33dfeb0d04b50f33fa4bbbc68e3c3a21da64b7cde3c8125f30b8071803575d925199468d1adb

test:
  secret_key_base: 4ba3897b5ffc0631d10aca2863485c7a67a5e3b111bc444d3e93b3685faf2d87ef8f8a03204d3ac6d7d0ec846c9a375513b49d60c6a4118b465d36c632ba5b31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
